spring:
  liquibase:
    change-log: db/changelog/changelog-master.xml
  profiles:
    active: h2
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  main:
    banner-mode: off
telegram:
  token:
  username:
  path:

